export class Constants {
  USDC_ID = 0;
  ETH_ID = 1;
  ETH_USDC_MARKET_ID = 1;

  USDC_DECIMALS = 20;
  ETH_DECIMALS = 18;
  PRICE_BUFFER_DECIMALS = 10;
  PRICE_BUFFER_DELTA_MULTIPLIER_DECIMALS = 10;

  ETH_USDC_MARKET_TICK_SIZE = 1e8;

  FUNDING_RATE_MULTIPLIER_DECIMALS = 10;
  FUNDING_RATE_DECIMALS = 16;
}
